extends: stylelint-config-standard

rules:
  indentation:
    - 4
    - indentInsideParens: once-at-root-twice-in-block

  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - tailwind
      - apply
      - screen
      - variants
      - responsive

  at-rule-empty-line-before:
    - always
    - except:
        - after-same-name
        - inside-block
      ignore:
        - after-comment
        - blockless-after-blockless
